### ISSUE TITLE
Generated code refers to `once_cell` and `colored`

### ISSUE THREAD

**Issue by andrewbaxter** [igordejanovic/rustemo#15]
**Describe the bug**
The generated code refers to modules `once_cell` and `colored` that might not be dependencies of the consuming project.  Since the user may never use these crates directly, they shouldn't be required to import them either.

FWIW I think it's common to republish the dependencies used by generated code and have the generated code refer to them within the republished namespace.

**Comment by igordejanovic** [comment]
Thanks. Republishing seems like a good idea. That would bring dependencies to `rustemo` crate only. I'll look into it.
