### ISSUE TITLE
Disabling debug print on debug mode

### ISSUE THREAD

**Issue by stevefan1999-personal** [igordejanovic/rustemo#4]
I don't want to garble up my stdout, and rather have those debug information on a separate file stream for better accessibility, because console buffer is line-limited.

**Comment by igordejanovic** [comment]
Added `--notrace` option for suppressing debug trace. In addition, debug trace is printed to std error so it can be redirected like:
```sh
rcomp mygrammar.rustemo 2>log.txt
```
Alternatively, `--notrace` can be controlled by env variable `RUSTEMO_NOTRACE`:
```
RUSTEMO_NOTRACE=1 rcomp mygrammar.rustemo
```
