### ISSUE TITLE
Regex lexer issues

### ISSUE THREAD

**Issue by tadeokondrak** [igordejanovic/rustemo#9]
The regex lexer generates code like: `Lazy::new(|| { Regex::new(concat!("^", "<regex goes here>")).unwrap() })`

This can go wrong when the regex looks something like `A|B|C`, because the intended regex is `^(A|B|C)` but the actual regex is `^A|B|C` or equivalently `(^A)|B|C`.

**Comment by igordejanovic** [comment]
Added note to he regex recognizer section in the docs. Closing. Feel free to reopen if you think there is a better solution.
